import type { Product } from '../types/product'
import { MERCHANT_ID } from './mockUsers'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'iPhone 14 Pro',
    brand: 'Apple',
    category: 'smartphone',
    model: 'iPhone 14 Pro',
    storage: '128GB',
    color: 'Space Black',
    sku: 'IP14P-128-BLK',
    costPrice: 32000,
    salesPrice: 38900,
    type: 'new',
    status: 'available',
    merchantId: MERCHANT_ID,
    createdBy: 'admin-1',
    createdAt: '2024-01-10T09:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-2',
    name: 'Galaxy S23',
    brand: 'Samsung',
    category: 'smartphone',
    model: 'Galaxy S23',
    storage: '256GB',
    color: 'Phantom Black',
    sku: 'GS23-256-BLK',
    costPrice: 24000,
    salesPrice: 29900,
    type: 'new',
    status: 'available',
    merchantId: MERCHANT_ID,
    createdBy: 'admin-1',
    createdAt: '2024-01-12T09:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-3',
    name: 'iPad Air',
    brand: 'Apple',
    category: 'tablet',
    model: 'iPad Air 5th Gen',
    storage: '64GB',
    color: 'Starlight',
    sku: 'IPADAIR5-64-STL',
    costPrice: 18000,
    salesPrice: 22900,
    type: 'new',
    status: 'available',
    merchantId: MERCHANT_ID,
    createdBy: 'branch-1',
    createdAt: '2024-02-01T09:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-4',
    name: 'MacBook Air M2',
    brand: 'Apple',
    category: 'laptop',
    model: 'MacBook Air 13" M2',
    storage: '256GB',
    color: 'Midnight',
    sku: 'MBA13M2-256-MID',
    costPrice: 34000,
    salesPrice: 41900,
    type: 'new',
    status: 'unavailable',
    merchantId: MERCHANT_ID,
    createdBy: 'admin-1',
    createdAt: '2024-02-15T09:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-5',
    name: 'iPhone 13',
    brand: 'Apple',
    category: 'smartphone',
    model: 'iPhone 13',
    storage: '128GB',
    color: 'Midnight',
    sku: 'IP13-128-MID-U',
    costPrice: 17500,
    salesPrice: 21900,
    type: 'used',
    status: 'available',
    merchantId: MERCHANT_ID,
    createdBy: 'branch-2',
    createdAt: '2024-03-05T09:00:00.000Z',
    deletedAt: null,
  },
  {
    id: 'prod-6',
    name: 'AirPods Pro 2',
    brand: 'Apple',
    category: 'accessory',
    model: 'AirPods Pro 2nd Gen',
    color: 'White',
    sku: 'APP2-WHT',
    costPrice: 6500,
    salesPrice: 8900,
    type: 'new',
    status: 'available',
    merchantId: MERCHANT_ID,
    createdBy: 'admin-1',
    createdAt: '2024-03-20T09:00:00.000Z',
    deletedAt: null,
  },
]
