import type { UserAccount } from '../types/user'

export const MERCHANT_ID = 'merchant-1'
// Renamed away from "IFix" — that's the platform's own product name, and
// reusing it for the seeded demo merchant made the two impossible to tell
// apart once real multi-merchant data existed (a Super Admin's platform-
// level "IFix" and this merchant's workspace "IFix" looked identical).
export const MERCHANT_NAME = 'Siam Gadget Repair'

export const MOCK_USER_ACCOUNTS: UserAccount[] = [
  {
    id: 'super-1',
    name: 'Nida Pradit',
    staffId: 'SA-001',
    email: 'nida.super@ifix.dev',
    password: 'password123',
    phone: '081-000-0001',
    role: 'super_admin',
    status: 'active',
    isTemporaryPassword: false,
    createdBy: null,
    createdAt: '2023-11-01T09:00:00.000Z',
    activatedAt: '2023-11-01T09:15:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'owner-1',
    name: 'Ake Somsak',
    staffId: 'MO-001',
    email: 'ake.owner@ifix.dev',
    password: 'password123',
    phone: '081-000-0002',
    role: 'merchant_owner',
    merchantId: MERCHANT_ID,
    status: 'active',
    isTemporaryPassword: false,
    createdBy: 'super-1',
    createdAt: '2023-11-02T09:00:00.000Z',
    activatedAt: '2023-11-02T09:20:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'admin-1',
    name: 'Somchai Jaidee',
    staffId: 'MA-001',
    email: 'somchai.admin@ifix.dev',
    password: 'password123',
    phone: '081-000-0003',
    role: 'merchant_admin',
    merchantId: MERCHANT_ID,
    status: 'active',
    isTemporaryPassword: false,
    createdBy: 'owner-1',
    createdAt: '2023-11-05T09:00:00.000Z',
    activatedAt: '2023-11-05T09:30:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'branch-1',
    name: 'Malee Srisuk',
    staffId: 'BM-001',
    email: 'malee.branch@ifix.dev',
    password: 'password123',
    phone: '081-000-0004',
    role: 'branch_manager',
    merchantId: MERCHANT_ID,
    branch: 'Chiang Mai',
    status: 'active',
    isTemporaryPassword: false,
    createdBy: 'admin-1',
    createdAt: '2023-11-10T09:00:00.000Z',
    activatedAt: '2023-11-10T09:45:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'branch-2',
    name: 'Krit Wongsa',
    staffId: 'BM-002',
    email: 'krit.branch@ifix.dev',
    password: 'password123',
    phone: '081-000-0005',
    role: 'branch_manager',
    merchantId: MERCHANT_ID,
    branch: 'Phuket',
    status: 'active',
    isTemporaryPassword: false,
    createdBy: 'admin-1',
    createdAt: '2023-11-10T09:00:00.000Z',
    activatedAt: '2023-11-10T09:45:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'staff-1',
    name: 'Fon Buranee',
    staffId: 'ST-001',
    email: 'fon.staff@ifix.dev',
    password: 'password123',
    phone: '081-000-0006',
    role: 'staff',
    merchantId: MERCHANT_ID,
    branch: 'Khon Kaen',
    status: 'active',
    isTemporaryPassword: false,
    createdBy: 'admin-1',
    createdAt: '2023-11-15T09:00:00.000Z',
    activatedAt: '2023-11-15T09:50:00.000Z',
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'staff-2',
    name: 'Tong Phimchan',
    staffId: 'ST-002',
    email: 'tong.staff@ifix.dev',
    password: '4821-3390-1156',
    phone: '081-000-0007',
    role: 'staff',
    merchantId: MERCHANT_ID,
    branch: 'Bangkok HQ',
    status: 'created',
    isTemporaryPassword: true,
    createdBy: 'admin-1',
    createdAt: '2026-08-14T10:00:00.000Z',
    activatedAt: null,
    suspendedBy: null,
    suspendedAt: null,
    resetToken: null,
    resetTokenExpiresAt: null,
  },
  {
    id: 'staff-3',
    name: 'Nut Waree',
    staffId: 'ST-003',
    email: 'nut.staff@ifix.dev',
    password: 'password123',
    phone: '081-000-0008',
    role: 'staff',
    merchantId: MERCHANT_ID,
    branch: 'Bangkok HQ',
    status: 'suspended',
    isTemporaryPassword: false,
    createdBy: 'admin-1',
    createdAt: '2024-01-10T09:00:00.000Z',
    activatedAt: '2024-01-10T09:30:00.000Z',
    suspendedBy: 'admin-1',
    suspendedAt: '2026-06-01T09:00:00.000Z',
    resetToken: null,
    resetTokenExpiresAt: null,
  },
]

export function generateTempPassword(): string {
  const part = () => String(Math.floor(1000 + Math.random() * 9000))
  return `${part()}-${part()}-${part()}`
}

export const RESET_TOKEN_TTL_MS = 15 * 60 * 1000

export function generateResetToken(): string {
  const bytes = new Uint8Array(24)
  crypto.getRandomValues(bytes)
  return Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('')
}
